#################################################
# color variables from left to right:           #
# border background text indicator child_border #
#################################################

client.focused          #4F6D7D #6AA0BD #FFFFFF #4F6D7D #6AA0BD
client.focused_inactive #6AA0BD #4F6D7D #E3E3E3 #73D216 #292929
client.unfocused        #212121 #383838 #ACACAC #73D216 #292929
client.urgent           #FC4138 #F27835 #FFFFFF #F27835 #FC4138
client.placeholder      #1F1F1F #2B2B2B #A8A8A8 #73D216 #1F1F1F
client.background       #2B2B2B

