#################################################
# color variables from left to right:           #
# border background text indicator child_border #
#################################################

client.focused          #465178 #596EB5 #FFFFFF #465178 #596EB5
client.focused_inactive #596EB5 #465178 #DADADA #596EB5 #465178
client.unfocused        #212121 #383838 #DADADA #525252 #292929
client.urgent           #FC4138 #F27835 #FFFFFF #F27835 #FC4138
client.placeholder      #1F1F1F #2B2B2B #A8A8A8 #4C4C4C #1F1F1F
client.background       #2B2B2B
