#################################################
# color variables from left to right:           #
# border background text indicator child_border #
#################################################

client.focused          #5E4C3D #9C7E65 #FFFFFF #73D216 #9C7E65
client.focused_inactive #9C7E65 #5E4C3D #E3E3E3 #73D216 #1F1F1F
client.unfocused        #1F1F1F #2B2B2B #ACACAC #73D216 #1F1F1F
client.urgent           #FC4138 #F27835 #FFFFFF #F27835 #FC4138
client.placeholder      #1F1F1F #2B2B2B #A8A8A8 #73D216 #1F1F1F
client.background       #2B2B2B
