#################################################
# color variables from left to right:           #
# border background text indicator child_border #
#################################################

client.focused          #DDB996 #CC9560 #FFFFFF #73D216 #CC9560
client.focused_inactive #CC9560 #966230 #E3E3E3 #73D216 #1F1F1F
client.unfocused        #1F1F1F #2B2B2B #ACACAC #73D216 #1F1F1F
client.urgent           #FC4138 #F27835 #FFFFFF #F27835 #FC4138
client.placeholder      #1F1F1F #2B2B2B #A8A8A8 #73D216 #1F1F1F
client.background       #2B2B2B
