######
#Bell#
######

enable_audio_bell no
window_alert_on_bell no

########
#Colors#
########

background #171421
cursor     #FFFFFF
foreground #D0CFCC

color0  #171421
color1  #C01C28
color2  #26A269
color3  #A2734C
color4  #12488B
color5  #A347BA
color6  #2AA1B3
color7  #D0CFCC
color8  #5E5C64
color9  #F66151
color10 #33D17A
color11 #E9AD0C
color12 #2A7BDE
color13 #C061CB
color14 #33C7DE
color15 #FFFFFF

selection_background #FFFFFF
selection_foreground #171421

########
#Cursor#
########

cursor_blink_interval 0
cursor_shape          underline

#######
#Fonts#
#######

bold_font        auto
bold_italic_font auto
italic_font      auto
font_family      Iosevka Term ss09 Extended
font_size        12.5

######
#Term#
######

term xterm-256color

################
#Text Selection#
################

copy_on_select yes
mouse_map      left click ungrabbed mouse_handle_click selection
mouse_map      cmd+left click grabbed,ungrabbed mouse_handle_click link

#####
#EOF#
#####
