############################
#                          # Welcome to my Distrobox configuration.
# [|||||\ [|||||\ [X]  [X] #
# [|   |] [|   |/   \\//   # It is my recommendation to edit this file over using shell variables.
# [|   |] [||||]     XX    #
# [|   |] [|   |\   //\\   # This file does not represent all options available.
# [|||||/ [|||||/ [X]  [X] #
#                          # See https://github.com/89luca89/distrobox for more information.
############################

container_always_pull="1"
container_generate_entry=1
container_image_default="quay.io/toolbx-images/debian-toolbox:unstable"
container_manager="podman"
container_name_default="Siderius"
container_user_custom_home="$HOME/.local/share/containers/home/Siderius/"
non_interactive="1"
skip_workdir="1"

#########################
#Connect to host xserver#
#########################

xhost +si:localuser:$USER >/dev/null 2>&1
