######################################################################
#                                                                    #
# Order the following color specifications from left to right:       #
#                                                                    #
# class -> border -> background -> text -> indicator -> child border #
#                                                                    #
######################################################################

client.focused          #78AEED #3584E4 #FFFFFF #2EC27E #3584E4
client.focused_inactive #1C71D8 #1A5FB4 #FFFFFF #26A269 #1A5FB4
client.unfocused        #1E1E1E #242424 #FFFFFF #26A269 #242424
client.urgent           #F8E45C #CD9309 #000000 #FF7800 #F8E45C
client.placeholder      #3D3846 #241F31 #FFFFFF #5E5C64 #3D3846
client.background       #000000
