###################################################################################
# USE THIS RULE TO ENABLE GAPS AND DISABLE THE TITLE BAR                          #
###################################################################################
# borders and edge/window gapping                                                 #
###################################################################################
# other rules with the 'for_window' flag should go in $HOME/.config/i3/rules.conf #
###################################################################################

for_window [class="^.*"] border pixel 1
gaps inner 5
smart_gaps on
hide_edge_borders smart

#################################################
# colorization and fonts                        #
#################################################
# from left-to-right:                           #
# border background text indicator child_border # 
#################################################

font xft:Hack
title_align center

client.focused          #2980B9 #3DAEE9  #EFF0F1 #27AE60 #3DAEE9
client.focused_inactive #606468 #31363B  #EFF0F1 #27AE60 #606468
client.unfocused        #606468 #31363B  #EFF0F1 #27AE60 #606468
client.urgent           #F67400 #ED1515  #804453 #ED1515 #F67400
client.placeholder      #606468 #232629  #EFF0F1 #4D4D4D #606468
client.background       #232629
