#######################################################
# automatically run the default scratchpad on startup #
#######################################################

exec --no-startup-id urxvt -name scratchpad 

####################################################
# automatically run common programs as scratchpads #
####################################################

exec --no-startup-id urxvt -e alsamixter
exec --no-startup-id urxvt -e vifm 

####################################################
# and that's it! I use xinitrc for everything else #
####################################################
