#############################################################################
# automatically run the terminal as a dropdown/scratchpad on startup        #
#############################################################################

exec --no-startup-id urxvt -name dropdown

####################################################
# and that's it! I use xinitrc for everything else #
####################################################
