#########################
# set defined variables #
#########################

set $col0  #101010
set $col1  #7c7c7c
set $col2  #8e8e8e
set $col3  #a0a0a0
set $col4  #686868
set $col5  #747474
set $col6  #868686
set $col7  #b9b9b9
set $col8  #525252
set $col9  #7c7c7c
set $col10 #8e8e8e
set $col11 #a0a0a0
set $col12 #686868
set $col13 #747474
set $col14 #868686
set $col15 #f7f7f7


#                       border  background text  indicator child_border
client.focused          $col7   $col7      $col8 $col15    $col7
client.focused_inactive $col0   $col4      $col7 $col3     $col1
client.unfocused        $col0   $col0      $col7 $col15    $col4
client.urgent           $col15  $col7      $col8 $col3     $col7
client.placeholder      #col7   #col0      $col7 $col15    $col3

client.background       #101010


