#################
# LEFT TO RIGHT #
#################
# border        #
# background    #
# text          #
# indicator     #
# child border  #
#################

client.focused          #3498DB #3498DB #FFFFFF #14161B   #3498DB
client.focused_inactive #14161B #1B1D24 #D4D7D7 #3498DB   #14161B
client.unfocused        #14161B #1B1D24 #D4D7D7 #14161B   #14161B
client.urgent           #3498DB #3498DB #FFFFFF #3498DB   #3498DB
client.placeholder      #1E2128 #1E2128 #6B6C73 #1E2128   #1E2128
client.background       #1B1D24
