#################
# LEFT TO RIGHT #
#################
# border        #
# background    #
# text          #
# indicator     #
# child border  #
#################

client.focused          #8AB4F8 #8AB4F8 #000000 #1967D2   #8AB4F8
client.focused_inactive #121212 #8AB4F8 #000000 #8AB4F8   #121212
client.unfocused        #121212 #272727 #EEEEEE #121212   #121212
client.urgent           #C58AF9 #C58AF9 #000000 #9334e6   #C58AF9
client.placeholder      #121212 #272727 #EEEEEE #121212   #121212
client.background       #121212
