#################
# LEFT TO RIGHT #
#################
# border        #
# background    #
# text          #
# indicator     #
# child border  #
#################

client.focused          #274164 #3465A4 #FFFFFF #274164   #3465A4
client.focused_inactive #14161B #1B1D24 #D4D7D7 #14161b   #14161B
client.unfocused        #14161B #1B1D24 #D4D7D7 #14161B   #14161B
client.urgent           #448AFF #82B1FF #000000 #448AFF   #448AFF
client.placeholder      #1E2128 #1E2128 #6B6C73 #1E2128   #1E2128
client.background       #1B1D24
