#########################
# modifier key settings #
#########################

set $mod Mod4
floating_modifier $mod

########################################################################################
# all other keybindings are done through i3-msg via sxhkd, see ~/.config/sxhkd/sxhkdrc #
########################################################################################
