#########
# focal #
#########

focus_follows_mouse no

###############################################################
# focal disable                                               #
###############################################################
# these disable ALL the mouse-based window switching defaults #
###############################################################

bindsym button1 nop
bindsym button2 nop
bindsym button3 nop
bindsym button4 nop
bindsym button5 nop

#####################################################################
# you can find the other keybindings in $HOME/.config/sxhkd/sxhkdrc #
#####################################################################
