##############################################################
# borders and gaps                                           #
##############################################################
# I don't use gaps anymore since ditching the bar, I think   #
# that, personally there's no use if you wanted to maximize  # 
# screen real-estate in your workflow                        #
############################################################## 
# see $HOME/.config/i3/rules.conf for enabling gaps          #                                                
############################################################## 
# gaps inner|outer|horizontal|vertical|top|right|bottom|left #
# current|all set|plus|minus|toggle <px>                     #
##############################################################
# examples for borders                                       #
##############################################################
# smart_borders on                                           #
# smart_borders no_gaps                                      #
# hide_edge_borders smart_no_gaps                            #
##############################################################
# examples for gaps                                          #
##############################################################
# gaps inner all set 20                                      #
# gaps outer current plus 5                                  #
# gaps horizontal current plus 40                            #
# gaps outer current toggle 60                               #
# smart_gaps on                                              #
# smart_gaps inverse_outer                                   #
##############################################################
# "smart_gaps inverse_outer" enables outer gaps when there's #
# only one container in the workspace                        #
##############################################################
# "gaps inner" by itself sets all gaps and struts equally    #
##############################################################

hide_edge_borders smart

#################################################
# colorization and fonts                        #
#################################################
# from left-to-right:                           #
# border background text indicator child_border # 
#################################################

font xft:Noto Mono
title_align center

client.focused          #1D99F3 #3DAEE9  #EFF0F1 #27AE60 #3DAEE9
client.focused_inactive #606468 #31363B  #EFF0F1 #27AE60 #606468
client.unfocused        #606468 #31363B  #EFF0F1 #27AE60 #606468
client.urgent           #F67400 #ED1515  #FCFCFC #ED1515 #F67400
client.placeholder      #606468 #232629  #EFF0F1 #4D4D4D #606468
client.background       #232629
