##############################################################
# borders and gaps                                           #
##############################################################
# see $HOME/.config/i3/rules.conf for enabling gaps & struts #
############################################################## 
# gaps inner|outer|horizontal|vertical|top|right|bottom|left #
# current|all set|plus|minus|toggle <px>                     #
##############################################################
# examples for borders                                       #
##############################################################
# smart_borders on                                           #
# smart_borders no_gaps                                      #
# hide_edge_borders smart_no_gaps                            #
##############################################################
# examples for gaps                                          #
##############################################################
# gaps inner all set 20                                      #
# gaps outer current plus 5                                  #
# gaps horizontal current plus 40                            #
# gaps outer current toggle 60                               #
# smart_gaps on                                              #
# smart_gaps inverse_outer                                   #
##############################################################
# "smart_gaps inverse_outer" enables outer gaps when there's #
# only one container in the workspace                        #
##############################################################
# "gaps inner" by itself sets all gaps and struts equally    #
##############################################################

smart_borders on

###################
# fonts and title #
###################

font xft: JetBrains Mono Medium 
title_align center

#################################
# THEME INCLUDES SWITCHBOARD    #
#################################
# uncomment only one at a time! #
#################################
# no bar color included, sorry! #
#################################

#include $HOME/.config/i3/themes/dracula/dracula.conf
#include $HOME/.config/i3/themes/Mint-Y/Aqua.conf
#include $HOME/.config/i3/themes/Mint-Y/Blue.conf
#include $HOME/.config/i3/themes/Mint-Y/Brown.conf
#include $HOME/.config/i3/themes/Mint-Y/Green.conf
#include $HOME/.config/i3/themes/Mint-Y/Grey.conf
#include $HOME/.config/i3/themes/Mint-Y/Orange.conf
#include $HOME/.config/i3/themes/Mint-Y/Pink.conf
#include $HOME/.config/i3/themes/Mint-Y/Purple.conf
#include $HOME/.config/i3/themes/Mint-Y/Red.conf
#include $HOME/.config/i3/themes/Mint-Y/Sand.conf
#include $HOME/.config/i3/themes/Mint-Y/Teal.conf
include $HOME/.config/i3/themes/nord/nord.conf
