##############################################################
# borders and gaps                                           #
##############################################################
# I don't use gaps anymore since ditching the bar, I think   #
# that, personally there's no use if you wanted to maximize  # 
# screen real-estate in your workflow                        #
############################################################## 
# see $HOME/.config/i3/rules.conf for enabling gaps          #                                                
############################################################## 
# gaps inner|outer|horizontal|vertical|top|right|bottom|left #
# current|all set|plus|minus|toggle <px>                     #
##############################################################
# examples for borders                                       #
##############################################################
# smart_borders on                                           #
# smart_borders no_gaps                                      #
# hide_edge_borders smart_no_gaps                            #
##############################################################
# examples for gaps                                          #
##############################################################
# gaps inner all set 20                                      #
# gaps outer current plus 5                                  #
# gaps horizontal current plus 40                            #
# gaps outer current toggle 60                               #
# smart_gaps on                                              #
# smart_gaps inverse_outer                                   #
##############################################################
# "smart_gaps inverse_outer" enables outer gaps when there's #
# only one container in the workspace                        #
##############################################################
# "gaps inner" by itself sets all gaps and struts equally    #
##############################################################

hide_edge_borders smart

#################################################
# colorization and fonts                        #
#################################################
# from left-to-right:                           #
# border background text indicator child_border # 
#################################################

font xft:Noto Mono
title_align center

client.focused          #191919 #8FA876  #FFFFFF #191919 #8FA876
client.focused_inactive #191919 #606060  #DADADA #8FA876 #262626
client.unfocused        #191919 #272727  #D3D3D3 #8FA876 #262626
client.urgent           #FC4138 #FF791A  #000000 #FC4138 #FF791A
client.placeholder      #191919 #232323  #A8A8A8 #373737 #191919
client.background       #232323
