#######################################
# rule to enable edge and window gaps #
#######################################

for_window [class="^.*"] border pixel 1

###############
# float rules #
###############

for_window [window_role="About"]  floating enable
for_window [window_role="Splash"] floating enable
for_window [class="Calc"]         floating enable
for_window [class="XClock"]       floating enable
for_window [class="Yad"]          floating enable

##############
# scratchpad #
##############

for_window [instance="scratchpad"] move window to scratchpad, scratchpad show
exec --no-startup-id urxvt --class scratchpad

################################
# assign clients to workspaces #
################################

assign [class="Firefox"]      1
assign [class="thunderbird"]  2
assign [class="mpv"]          3
assign [class="Imager"]       4
assign [class="Lxappearance"] 4
assign [class="XClock"]       4
assign [class="Calc"]         5
assign [class="libreoffice"]  5
