###################
# name workspaces #
###################

set $ws1 
set $ws2 
set $ws3 
set $ws4
set $ws5
set $ws6

################################################
# set the default layout across all workspaces #
################################################

workspace_layout default 

############################
# workspace back and forth #
############################

workspace_auto_back_and_forth yes

###################################################################################
# setting this option allows a workspace to steal focus during window activations #
###################################################################################
# other rules with the 'for_window' flag should go in $HOME/.config/i3/rules.conf #
###################################################################################

for_window [urgent=latest] focus
