########################################################
#Aesthetic stuff, some less important details, go here.#
#USE GAPS RESPONSIBLY, PEOPLE!                         #
######################################################################
#Coloring the Window Decorations in the given order:                 #
#<colorclass> <border> <background> <text> <indicator> <child_border>#
######################################################################

client.focused          #0C427D #0C75DE #FFFFFF #73D216 #0C75DE
client.focused_inactive #292929 #525252 #DADADA #73D216 #292929
client.unfocused        #292929 #383838 #DADADA #525252 #292929
client.urgent           #F27835 #FC4138 #FFFFFF #F27835 #FC4138
client.placeholder      #292929 #383838 #DADADA #525252 #292929
client.background       #383838

######################################
#Adjust Borders and Remove Title Bars#
######################################

default_border pixel          2
default_floating_border pixel 2

##################################
#Fonts, for the Bar and Titlebars#
##################################

font pango: Iosevka ss12 Extended Bold
title_align center

##################################
#Gaps, for Your r/unixporn Needs!#
##################################

gaps inner 10

##################################
#Borders and Gaps can be Disabled#
#if There's Only One Window Open.#
##################################
#Smart Borders#
###############

smart_borders on

############
#Smart Gaps#
############

smart_gaps on
