##################################
#Specify i3 Bar Here, if Required#
###########################################
#Coloration follows this order:           #
#<colorclass> <border> <background> <text>#
###########################################

bar {
      status_command i3status
      
      font pango:Iosevka ss12, Symbols Nerd Font Mono
      separator_symbol "|"

      tray_padding 0
      colors {

               background         #383838
               separator          #292929
               statusline         #DADADA

               binding_mode       #292929 #F27835 #FFFFFF
               
               active_workspace   #292929 #525252 #DADADA
               focused_workspace  #07427D #0C75DE #FFFFFF
               inactive_workspace #292929 #383838 #DADADA
               urgent_workspace   #FC4138 #F27835 #000000

      }
}
