############################################################################
#A NOTE ON VARIABLES: If you specify a variable in a file, you NEED to call#
#that variable from within the same file.                                  #
############################################################################
#Let's establish some variables to make assigning things cleaner/easier#
########################################################################
#Applications and Utilities#
############################

set $browser     flatpak run io.gitlab.librewolf-community
set $filechooser filechooser.sh
set $mail        flatpak run eu.betterbird.Betterbird
set $menu        dmenu_run -l 10
set $screenshot  scrot $HOME/Pictures/Scrot/%c.png
set $term        i3-sensible-terminal

###########
#Modifiers#
###########

set               $mod Mod4
floating_modifier $mod

##############
#Focus Method#
##############

set $down  Down
set $left  Left
set $right Right
set $up    Up

####################
#Terminal Launchers#
####################

bindsym $mod+Menu   exec --no-startup-id $menu
bindsym $mod+Return exec --no-startup-id $term
bindsym Mod1+Return exec --no-startup-id $term -name scratchpad

#######################
#XF86 Common Shortcuts#
#######################

bindsym XF86Calculator exec --no-startup-id $term -e bc -q
bindsym XF86Explorer   exec --no-startup-id $filechooser
bindsym XF86HomePage   exec --no-startup-id $browser
bindsym XF86Mail       exec --no-startup-id $mail

#################
#XF86 Multimedia#
#################

bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

###################
#Take a Screenshot#
###################

bindsym Print exec --no-startup-id $screenshot

#################
#Window Focusing#
#################

bindsym $mod+$down  focus down
bindsym $mod+$left  focus left
bindsym $mod+$right focus right
bindsym $mod+$up    focus up

bindsym $mod+Tab       focus next
bindsym $mod+Shift+Tab focus prev
