#########################################################
#It's helpful to launch programs upon your login manager#
#or startx invocation of i3, and for some important     #
#stuff, like policykit (polkit), it's best to add them  #
#to your config file's autostart section.               #
#########################################################
#Policykit, so we can access a password prompt if#
#needed. Otherwise we lose important access...   #
##################################################

exec --no-startup-id /usr/bin/mate-polkit

##################################
#Bluetooth Object Exchange (OBEX)#
##################################

exec --no-startup-id systemctl --user start obex

###################################
#Display Compositor, for Eye Candy#
###################################

exec --no-startup-id picom

###############
#Notifications#
###############

exec --no-startup-id dunst

###############
#Screen locker#
###############

exec --no-startup-id xautolock -time 10 -locker slock

############
#Xresources#
#####################################################################
#Setting cursor size via xresources isn't being done gracefully,    #
#so we fix it by appending "i3-msg restart" at the end of the string#
#####################################################################

exec --no-startup-id xrdb -merge $HOME/.config/X11/xresources && i3-msg restart

################################
#Automatically hide the xcursor#
################################

exec --no-startup-id xbanish -t 5

####################################################
#Execute items ALWAYS after reloading/restarting i3#
####################################################
#Background color/image setting#
################################

exec_always --no-startup-id hsetroot -fill $HOME/Pictures/Wallpapers/Pexels/Marek\ Piwnicki/pexels-marek-piwnicki-skyfall.jpg
