###############################################################
#Set here windows desired (or even required) to be floating,  #
#this helps the quality of life for certain applications which#
#do NOT tile well at all.                                     #
###############################################################
#WM_CLASS#
##########

#########
#WM_NAME#
#########

#########
#WM_ROLE#
#########

for_window [window_role="About|about"] floating enabled

