###################
#Focus on hovering#
###################

focus_follows_mouse yes

#####################################
#Allow focus stealing by new windows#
#####################################

for_window [urgent="latest"] focus
