#########
# Class #
#########

assign [class="Librewolf|thunderbird"] 1
assign [class="discord|Telegram"] 2
assign [class="FreeTube|mpv"] 4
assign [class="libreoffice"] 6

#########
# Title #
#########

assign [title="btop|htop|top"] 3
