#########################################
# Edit this include for the colorscheme #
#########################################

include $XDG_CONFIG_HOME/i3/config.d/colors.d/Adwaita-dark.conf

##########################
# Font for window titles #
##########################

font pango: Monospace
title_align center

#####################################################################################
# Universal rule to enable gaps and hide titlebars on floating and tiled containers #
#####################################################################################
# NOTICE: title bars are visible for stacked and tabbed containers                  #
#####################################################################################

for_window [class="^.*"] border pixel 2
gaps inner 5

##########################################################################
# Use these automatic settings for whenever there's only one window open #
##########################################################################

smart_borders on
smart_gaps on
