#########################################################################################################
# For those that use a bar, put your bar configurations in $XDG_CONFIG_HOME/.config/i3/config.d/bars.d/ #
# and edit the below include line for your preferred setup.                                             #
#########################################################################################################

include $XDG_CONFIG_HOME/i3/config.d/bars.d/nobar.conf
