#####################################################################################
# All floating window rules are organized by class, instance, role, title, and type #
#####################################################################################

#########
# Class #
#########

for_window [class="Lxappearance"] floating enable, sticky enable 

############
# Instance #
############

#########
# Title #
#########

for_window [title="About LibreWolf"] floating enable, border pixel 0
