#####################################################################################
# Focus by mouse hover. This is a natural way of focusing but not always desirable. #
# Set "focus_follows_mouse" to "no" to disable sloppy (hover) focusing.             #
#####################################################################################

focus_follows_mouse no

################################################################################################
# no_focus rules exclude select windows from gaining focus, either automatically or explicitly #
################################################################################################
# window_role                                                                                  #
################################################################################################

no_focus [window_role="Popup"]
