#########################################################################################################################
# Edit the include below to select a per-monitor output configuration placed in $XDG_CONFIG_HOME/i3/config.d/outputs.d/ #
#########################################################################################################################

include $XDG_CONFIG_HOME/i3/config.d/outputs.d/monitor0.conf
