#########################################################################################################
# Scratchpads are floating windows that persist in the background and can be toggled in and out of view #
#########################################################################################################
# By Instance. Use 'xprop' to grab the window specifications for WM_CLASS, WM_NAME, WM_ROLE, & WM_TYPE  #
#########################################################################################################

for_window [instance="scratchpad"] move scratchpad, scratchpad show, resize set 1000 750, move position center

for_window [instance="fzf_run"] move scratchpad, scratchpad show, resize set 500 250, move position center, border pixel 1
