for_window [instance="scratchpad"] move scratchpad, scratchpad show, resize set 850 550, move position center, sticky enable

for_window [instance="fzf_run"] move scratchpad, scratchpad show, resize set 450 200, move position center, border pixel 1
