######################################################################
#Binding modes are keybinding sets that have been sectioned off from #
#the top layer, IE your default/normal keyboard inputs. HIGHLY useful#
#if you use a compact keyboard %(60) or a restrictive laptop keyboard#
#where avoiding overlap by any means is preferred.                   #
######################################################################
#DO MAKE SURE TO HAVE AN ESCAPE TO "default" OR YOU WILL BE STUCK#
##################################################################
#Kill Window#
#############

bindsym Control+Mod1+x mode "kill"
mode "kill" {

              bindsym Mod1+x xkill
              bindsym x kill

              bindsym Escape mode "default"

}

#########
#Layouts#
#########

bindsym Control+Mod1+l mode "layout"
mode "layout" {

                bindsym f          floating toggle
                bindsym h          splith
                bindsym v          splitv   
                bindsym Mod1+h     layout splith
                bindsym Mod1+s     layout stacking
                bindsym space      layout toggle split
                bindsym Mod1+space split toggle
                bindsym t          layout tabbed
                bindsym v          layout splitv

                bindsym Escape mode "default"

}

########
#Moving#
########

bindsym Control+Mod1+m mode "move"
mode "move" {

              bindsym c move position center

              bindsym Left   move left
              bindsym Down   move down
              bindsym Up     move up
              bindsym Right  move right

              bindsym Escape mode "default"

}

##########
#Resizing#
##########

bindsym Control+Mod1+r mode "resize"
mode "resize" {

                bindsym Left   resize shrink width  10 px or 10 ppt
                bindsym Down   resize grow   height 10 px or 10 ppt
                bindsym Up     resize shrink height 10 px or 10 ppt
                bindsym Right  resize grow   width  10 px or 10 ppt

                bindsym Escape mode   "default"

}

#########
#Session#
#########

bindsym Control+Mod1+Delete mode "session"
mode "session"{

                bindsym c reload
                bindsym r restart

                #######################################################
                #Using i3-nagbar as a session-menu-ish tool,          #
                #refer to the default config file for more information#
                #######################################################

                bindsym Control+Mod1+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
                bindsym Control+Mod1+l exec "i3-nagbar -t warning -m 'You pressed the lock screen shortcut. Do you really want to lock your screen?' -B 'Yes, lock my screen' 'slock'
                bindsym Control+Mod1+p exec "i3-nagbar -t warning -m 'You pressed the suspend shortcut. Do you really want to suspend your system?' -B 'Yes, suspend my system' 'systemctl suspend -i'
                bindsym Control+Mod1+r exec "i3-nagbar -t warning -m 'You pressed the reboot shortcut. Do you really want to reboot your system?' -B 'Yes, reboot my system' 'systemctl reboot'
                bindsym Control+Mod1+s exec "i3-nagbar -t warning -m 'You pressed the shutdown shortcut. Do you really want to shutdown your system?' -B 'Yes, shutdown my system' 'systemctl poweroff'

                bindsym Escape mode "default"

}
