######################################################################
#Scratchpads are centered, floating windows that do not acknowledge a#
#current given workspace and hide in the background until needed.    #
######################################################################
#Let's set a general rule for which scratchpads to default to#
##############################################################

for_window [instance="scratchpad"] move scratchpad, resize set 70 ppt 70 ppt, \
                                   scratchpad show, move position center, sticky enable

######################################################
#Set a keybinding to toggle them in and out of hiding#
######################################################

bindsym Control+Return scratchpad show

#############################
#Move a Window to Scratchpad#
#############################

bindsym Control+Shift+Return move scratchpad
