#################################################################
#Tabbed Windows are Horizontally-Aligned Containers, Very Useful#
#################################################################
#WM_CLASS#
##########

for_window [class="TelegramDesktop"] layout tabbed

#########
#WM_NAME#
#########

################
#WM_WINDOW_ROLE#
################

for_window [window_role="3pane|browser"] layout tabbed
