###########
#Modifiers#
###########

set $mod Mod4

##################################################################
#Automatically Switch to and from Current and Previous Workspaces#
##################################################################

workspace_auto_back_and_forth yes
bindsym $mod+b workspace back_and_forth

###################
#Naming Workspaces#
#############################################################
#REMINDER: Set your keybindings BELOW the assigned variables#
#in order to see their names.                               #
#############################################################

set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6

#####################
#Workspace Switching#
#####################

bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6

bindsym $mod+bracketleft workspace prev
bindsym $mod+bracketright workspace next

############################################
#Mode to send windows to desired workspaces#
####################################################
#For functionality's sake I'm placing a mode here  #
#instead of in $HOME/.config/i3/config.d/mode.conf,#
#see the file for more keybinding modes...         #
####################################################

bindsym Control+Mod1+w mode "movecon"
mode "movecon" {

                bindsym 1 move container to workspace $ws1, workspace $ws1
                bindsym 2 move container to workspace $ws2, workspace $ws2
                bindsym 3 move container to workspace $ws3, workspace $ws3
                bindsym 4 move container to workspace $ws4, workspace $ws4
                bindsym 5 move container to workspace $ws5, workspace $ws5
                bindsym 6 move container to workspace $ws6, workspace $ws6

                bindsym bracketleft move container to workspace prev, workspace prev
                bindsym bracketright move container to workspace next, workspace next
                
                bindsym Escape mode "default"

}

#######################
#Workspace Assignments#
#######################
#WM_CLASS#
##########

assign [class="betterbird|LibreWolf"]     $ws1
assign [class="TelegramDesktop|WebCord"]  $ws2
assign [class="FreeTube|mpv"]             $ws3

#############
#By Instance#
#############

assign [instance="DesktopEditors"]  $ws4

