#!/bin/sh

# Composite Manager

picom &

# Notification Service

dunst &

# PolicyKit Authentication Agent

/usr/libexec/polkit-mate-authentication-agent-1 &

# Screen Locker

xautolock -time 10 -locker slock &

# Sound Server

/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/wireplumber &

# Wallpaper

xwallpaper --stretch $HOME/Pictures/Wallpapers/greybird-theme/greybird.png &

# Xcursor Correction for Various WMs

xsetroot -cursor_name left_ptr &

# Xresources

xrdb -merge $XRESOURCES &

# Start Session

exec dbus-run-session -- ratpoison -f $RATPOISONRC
