#!/bin/sh

#################
#Autohide Cursor#
#################

xbanish -t 5 &

############
#Background#
############

hsetroot -solid "gray10" &

############
#Compositor#
############

picom -b &

######
#Dbus#
######

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --exit-with-session --sh-syntax)"
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY
fi

##############
#Desktop Apps#
##############

sleep 2 &&
xcalc & 

sleep 2 &&
xclock &

###############
#Notifications#
###############

dunst &

########
#Polkit#
########

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

##############
#Screenlocker#
##############

xautolock -time 10 -locker slock &

###########
#Setxkbmap#
###########

setxkbmap -option caps:swapescape &

############
#Xresources#
############

xrdb -merge "$XRESOURCES" &

##########
#Xsession#
##########

exec cwm -c "$CWMRC"
