#!/bin/sh


##############################################
# correct virtual machine display resolution #
##############################################

#xrandr --output Virtual-1 --auto &

#################
# hotkey daemon #
#################

sxhkd &

#####################
# reload xresources #
#####################

xrdb -merge $XRESOURCES &

########################
# set background color #
########################

xsetroot -solid "#241F31" &

#######################
# correct the xcursor #
#######################

xsetroot -cursor_name left_ptr &

######################
# start the xsession #
######################

exec nowm_focuswatcher.sh
