#!/usr/bin/env bash

####################################################################
# the common and-or most logical areas to search for applications  #
####################################################################
# specify /usr/bin (standard $PATH) if you like, but I personally  #
# don't want a bunch of crap you can't actually launch in the menu #
####################################################################

DIRS=(
  /usr/bin
)

#######################################
# ABOUT: Run="$()"                    #
#######################################
# the "|" is a pipe-through function  #
# the "\" is a line break, essential  #
# "ls" lists the directory contents   #
# "uniq -u" ignores duplicate entries #
# the various "--" flags are optional #
#######################################

Run="$(ls $DIRS | \
	uniq -u | \
	fzf \
	-e -i -x \
	--border=sharp \
	--color='16' \
	--margin='1,2' \
	--no-info \
	--no-mouse \
	--no-multi \
	--prompt='Run: ' \
       	--reverse)"

###################################################
# NOTICE: the "nohup" flag, or no-hang-up, allows #
# the terminal to exit gracefully upon selection  #
# and detach from the child process altogether    #
###################################################
# NOTICE: ">/dev/null 2>&1" prevents nohup from   #
# littering $HOME with a "nohup.out" logging file #
# every time an entry is selected, do not touch   #
###################################################

exec nohup $Run >/dev/null 2>&1
