#################################################
# color variables from left to right:           #
# border background text indicator child_border #
#################################################

client.focused          #8FBCBB #8FBCBB #2E3440 #A3BE8C #88C0D0
client.focused_inactive #81A1C1 #81A1C1 #2E3440 #A3BE8C #5E81AC
client.unfocused        #5E81AC #5E81AC #2E3440 #B48EAD #5E81AC
client.urgent           #BF616A #D08770 #2E3440 #EBCB8B #BF616A
client.placeholder      #3B4252 #3B4252 #D8DEE9 #E5E9F0 #3B4252
client.background       #2E3440
