#################################################
# color variables from left to right:           #
# border background text indicator child_border #
#################################################

client.focused          #1F232B #88C0D0 #2E3440 #A3BE8C #88C0D0
client.focused_inactive #1F232B #5E81AC #2E3440 #A3BE8C #5E81AC
client.unfocused        #1F232B #3B4252 #D8DEE9 #A3BE8C #1F232B
client.urgent           #1F232B #D08770 #2E3440 #EBCB8B #BF616A
client.placeholder      #1F232B #2E3440 #ECEFF4 #A3BE8C #1F232B
client.background       #2E3440
